### ISSUE TITLE
Ex23 - step 32

### ISSUE THREAD

**Issue by Rafke13** [SAP-samples/teched2024-DA180#18]
I don't have the "More" menu option... that was when I was in full screen mode. However, when making my screen smaller (to take a clear screen shot) it all of a sudden appeared? Why is it not visible in full screen mode?

**Comment by kp-sauer** [comment]
These applications are built with a responsive web design, so the screen content adjusts depending on the screen/window size and the resolution. The screenshot you see was taken on a regular 14" laptop screen. If you have a larger screen or even a large external monitor, then it will certainly look different. 
Like the text in step 32 says, you are looking for the "Add New Data" button, which is a cube with a plus sign. The icon is part of Tools group of icons (you see File, Edit, Insert, View, etc. as a kind of group header for various icons).
This screenshot shows like it could look on a different screen:
![2024-11-06_15-44-02](https://github.com/user-attachments/assets/b9bc16df-51c0-489b-92ee-40846547d477)
