### ISSUE TITLE
SAP Datasphere Trial version instantly logs off

### ISSUE THREAD

**Issue by hiriudu** [SAP-samples/teched2024-DA180#9]
Hello,
Thank you for the exercise!
I was able to get a trial version of SAP Datasphere as indicated in the document. However, every time I log in with the user name and password provided by SAP, system logs me in and immediately logs out - with a message  - "Session Ended. Your session has timed out. Please log on again" 

![image](https://github.com/user-attachments/assets/9f28de4c-0fb6-460d-a298-90462bf23063)

I am using Google Chrome and have tried deleting browser cache and cookies with no luck. Same issue with Microsoft Edge as well. 
Is this a server issue or am I doing something wrong?

Thank you

**Comment by nikolabraukmueller** [comment]
Hello @hiriudu,

thanks for raising the topic. Could you please send the URL of the tenant your basic trial user was created for and the user name ?

Thanks, Nikola

**Comment by hiriudu** [comment]
Hi Nikola,
Thank you the quick response. 
Here's the link that I got in the email after setting up the trial system - 
https://basic-trial-datasphere.cfapps.us10.hana.ondemand.com/

This re-directs me to the below link with user name and password prompt  

[Re-direct](https://basic-trial-datasphere.cfapps.us10.hana.ondemand.com/saml2/idp/sso/academy.accounts.ondemand.com?SAMLRequest=pZJRT9swFIXf9ysiv8d23FZKrSaoW4WoxEZEAg%2B83TkONUrsLNfpxr%2Bfm1IBYvRlr9a55xzrO6uLP10b7fWAxtmMJJSTSFvlamMfM3JXXcYpuci%2FrBC6VvRyPfqdvdW%2FRo0%2BWiPqwYe7b87i2Omh1MPeKH13e52Rnfc9SsZAQa275xo8YL%2FTg44FheCirTcKDtd0xITTHVigzgYt2Joq17FDJCvLGwatAfy30W%2BMW7PXJNqEQsZOfh%2ByKSjlRuvxo79gpu4ZojuvJdGlG5Sefp%2BRBloMkdtNRkDwtEkNpJwrtVzwRcqfZk0jYNHMk0cRRFgAYqj4eoY46q1FD9ZnRHAxjxMe82WVzORiJudLKlLxQKJicN4p13419ghjHKx0gAalhU6j9EqW6%2B%2FXUlAufx5FKK%2BqqoiLm7Ii0f0JqjhADZgtyiPG8179SzDJj9Tl1Hh463DeAE67IPl%2Fr2DF3nbITzv8EUK3m8K1Rj0f2HTgP%2B%2BU0GR6MXXcTFI5Wuy1Mo3RNWH5S8b7ded%2FAQ%3D%3D&RelayState=cloudfoundry-uaa-sp&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=xSL3UTwDGOMXPar1YShc1ZbMuxqAb7fObm6qLfCEdN84LDhKCVZ%2FxJQ8jBBI3uBiNqBVhBkQLHTEHiIJdGINuT3q5BaT7hI2eoJXk458%2FTThnzKpxAXH0CQFXoTWn4AeQfdw1fAQOmfY%2BrEK%2BaI6trkf6AiVGbGHMIcD3YFDkwzVS1PtSOH8ubpbaF9Dv2Pid0xgpYIRZuvJJbkGaLPSZfpJ69q5iW0pH1MzJqKExICaYxfjqqxo6bjK9UM4l24XSECHy8Nckb7A%2FTwkCBLR9jwNq8%2FFD%2Foq%2FjudlrL8SC1ADyXmC8ikbcfPUEnbmv56TPVWXILo2V9AjY1C6%2Bkk5g%3D%3D)

After I log in, I am re-directed to this link - which logs me in but instantly times out

https://basic-trial-datasphere.cfapps.us10.hana.ondemand.com/dwaas-core/index.html#/home


Thank you

**Comment by nikolabraukmueller** [comment]
Hi @hiriudu ,

thanks! Could you please also send the user name?

**Comment by hiriudu** [comment]
Hi Nikola,
User name  - GE118526
Please let me know if you need me to send the password in a separate email?

Thank you

**Comment by nikolabraukmueller** [comment]
Hi @hiriudu,

we created a new user for you while we follow up on the issue you described.
Can you please contact me via the SAP TechEd Virtual Attendee Chat or email (_email address_)? Then I will send you the new user name and password.

Thanks for you patience!

**Comment by hiriudu** [comment]
Hi Nikola,
Thank you! I will reach out via your SAP email.

**Comment by nikolabraukmueller** [comment]
Hello @hiriudu,
based on your feedback via email, logon with the new user name and password was successful. 
Closing this issue, best regards
